# Generated by Django 4.2.8 on 2023-12-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='title',
            new_name='name',
        ),
    ]
