# Generated by Django 4.2.8 on 2023-12-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_release_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
