# Generated by Django 5.0.1 on 2024-01-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_category_release_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
    ]
